### ISSUE TITLE
Authenticated offline-enabled forms cannot upload submission after signing out. 

### ISSUE THREAD

**Issue by piqoni** [kobotoolbox/enketo-express#321]
How to reproduce:

1. Open an offline-enabled form.
2. Authenticate ( OpenRosa form authentication )
3. Click 'log out' when form is loaded. 
4. Re-open form URL and the form opens without any auth.
5. Now, if you try to submit form in this state you get a 'Failed (Offline?).' error message. And it is cumbersome to bring back the login page, because you have to clear browser's data. 

Logs:

    TypeError: Cannot read property 'user' of null
        at Request._callback (/home/user/enketo-express/app/lib/communicator/communicator.js:157:36)
        at Request.self.callback (/home/user/enketo-express/node_modules/request/request.js:198:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/home/user/enketo-express/node_modules/request/request.js:1073:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/home/user/enketo-express/node_modules/request/request.js:1019:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:943:16
        at process._tickCallback (node.js:419:13)
    Worker 15623 sadly passed away. It will be reincarnated.

**Comment by MartijnR** [comment]
Good one! I think the solution will be to clear the browser's form cache upon logout.

Thanks!

**Comment by MartijnR** [comment]
#4 should probably not be possible -> clear form cache
#5 should prompt a login message instead of 'Offline'. Not sure why browser data would have to be cleared when going to /login to reset a cookie.

Fix #5 first, then #4.

**Comment by MartijnR** [comment]
clearing form cache is not really feasible as some forms in the cache may not require authentication. Leaving it.

I understand the full issue with 5 now (the need to manually clear the cache). Turned into a new issue -> https://github.com/kobotoolbox/enketo-express/issues/368
