### ISSUE TITLE
Getting `EntityRef: expecting ';'` error

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#362]
Hi,
We are getting the following error in the screenshot when we upload a certain. Would you know what we are missing or why the error is being triggered?
<img width="1280" alt="screen shot 2015-11-30 at 10 00 18" src="https://cloud.githubusercontent.com/assets/1128227/11465389/5e96f246-9749-11e5-9236-3cd081344f45.png">

The following is the error message on my browser's console
```javascript
at Object.module.exports.fromXml (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/node_modules/libxslt/node_modules/libxmljs/lib/document.js:120:21)
    at /Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/src/transformer.js:92:28
    at tryToUnwrap (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/node_modules/lie/lib/index.js:171:5)
    at tryCatch (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/node_modules/lie/lib/index.js:183:17)
    at safelyResolveThenable (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/node_modules/lie/lib/index.js:174:16)
    at new Promise (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/node_modules/lie/lib/index.js:32:5)
    at _parseXml (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/src/transformer.js:90:12)
    at transform (/Users/ekisa/ona/repos/enketo-express/node_modules/enketo-transformer/src/transformer.js:32:12)
    at Promise_then_fulfilled (/Users/ekisa/ona/repos/enketo-express/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/Users/ekisa/ona/repos/enketo-express/node_modules/q/q.js:835:31)
```

**Comment by ivermac** [comment]
Just noticed it was an issue with the title having `&` character. Removing the character fixed the problem

**Comment by MartijnR** [comment]
Thanks. Pyxform seems to take care of changing & to &amp; If you have a
feature where the title can be changed dynamically, you'd probably want to
convert those html entities too.

On Mon, Nov 30, 2015 at 12:14 AM, Mark Ekisa <notifications@github.com>
wrote:

> Just noticed it was an issue with the title having & character. Removing
> the character fixed the problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/362#issuecomment-160542290>
> .
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>
