### ISSUE TITLE
EADDRINUSE null:8005

### ISSUE THREAD

**Issue by dwinetralizme** [kobotoolbox/enketo-express#528]
can you help me sir, iam install enketo with ubuntu 14.0 and i want to connect odkaggregate with enketo express. 
if execute npm start i get error like 
Error: bind EADDRINUSE null:8005
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at cb (net.js:1311:16)
    at rr (cluster.js:607:14)
    at Worker.<anonymous> (cluster.js:577:9)
    at process.<anonymous> (cluster.js:736:8)
    at emitTwo (events.js:105:20)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
Worker 10037 sadly passed away. It will be reincarnated.
events.js:154
      throw er; // Unhandled 'error' event

thanks

**Comment by MartijnR** [comment]
This means that there is already something else running on port 8005. Probably Enketo.

In case you are not already using this, here is the official installation guidance: http://blog.enketo.org/install-enketo-production-ubuntu/

**Comment by awemulya** [comment]
check netstat -ntlp
which port is using 8005 

or in some case something running on port 6380  "cache": {
            "host": "127.0.0.1",
            "port": "6379",
            "password": null
        }
