### ISSUE TITLE
Can not get /css/bootstrap-datepicker.css.map 

### ISSUE THREAD

**Issue by phongduong** [kobotoolbox/enketo-express#827]
I've installed ODK and Enketo. When i view form on ODK by Enketo it show this error
```
POST http://localhost:8006/transform/xform/::YYY8 500 (Internal Server Error)
Error: Internal Server Error
 at Object.<anonymous> (enketo-webform-bundle.min.js:1)
    at u (enketo-webform-bundle.min.js:1)
    at Object.fireWith [as rejectWith] (enketo-webform-bundle.min.js:1)
    at i (enketo-webform-bundle.min.js:1)
    at XMLHttpRequest.<anonymous> (enketo-webform-bundle.min.js:1) "Error: Internal Server Error
    at Object.<anonymous> (http://localhost:8006/js/enketo-webform-bundle.min.js:1:777119)
    at u (http://localhost:8006/js/enketo-webform-bundle.min.js:1:418832)
    at Object.fireWith [as rejectWith] (http://localhost:8006/js/enketo-webform-bundle.min.js:1:419598)
    at i (http://localhost:8006/js/enketo-webform-bundle.min.js:1:456630)
    at XMLHttpRequest.<anonymous> (http://localhost:8006/js/enketo-webform-bundle.min.js:1:461463)"
```

On terminal i got this
`GET /css/bootstrap-datepicker.css.map 404 617 - 101.925 ms`
Can you show me how to fix it?

**Comment by MartijnR** [comment]
This is only when you have the developer console open. One of the libraries that Enketo uses doesn't remove the css map reference. It won't do any harm though. It's just ugly.
 
I couldn't convince them to remove it: https://github.com/uxsolutions/bootstrap-datepicker/issues/1795 and it's not worth forking the library for that reason alone.

**Comment by MartijnR** [comment]
Looks like we should be able to get rid of this now. Thanks for bringing this up 👍.  I opened an issue here: https://github.com/enketo/enketo-core/issues/461
